<?php
namespace Packer;

/**
 * Test class for Packer.
 * Generated by PHPUnit on 2012-10-11 at 05:55:32.
 */
class PackerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Packer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Packer('php://temp');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Packer\Packer::write
     */
    public function testWrite() {
        $this->object->write('test', 'write');
    }

    /**
     * @covers Packer\Packer::keys
     * @todo Implement testKeys().
     */
    public function testKeys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Packer\Packer::exist
     * @todo Implement testExist().
     */
    public function testExist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Packer\Packer::read
     * @todo Implement testRead().
     */
    public function testRead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Packer\Packer::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Packer\Packer::delete
     * @todo Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
